# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
            ],
            options={
                'db_table': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Bicycles',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Bicycle')),
            ],
            options={
                'db_table': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('security', models.CharField(choices=[('0', 'none'), ('1', 'good'), ('2', 'high')], default='0', max_length=1)),
                ('amount', models.PositiveSmallIntegerField(default=3)),
                ('is_free', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Parkings',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('from_hour', models.IntegerField(blank=True, choices=[(0, '00'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], null=True)),
                ('to_hour', models.IntegerField(blank=True, choices=[(0, '00'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], null=True)),
                ('category_id', models.CharField(choices=[('0', 'store'), ('1', 'service'), ('2', 'cafe')], default='2', max_length=1)),
            ],
            options={
                'db_table': 'Places',
            },
        ),
        migrations.CreateModel(
            name='StolenBike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('day', models.DateField()),
                ('is_found', models.BooleanField(default=False)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Bicycle')),
            ],
            options={
                'db_table': 'StolenBikes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.URLField(blank=True)),
                ('role_id', models.CharField(choices=[('0', 'user'), ('1', 'admin')], db_index=True, default=0, max_length=1)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.User'),
        ),
        migrations.AddField(
            model_name='parking',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.User'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.User'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='parking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Parking'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Place'),
        ),
    ]
