# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(db_index=True, default=None, max_length=255),
        ),
    ]
