# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20161011_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='parking_id',
            new_name='parking',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='bicycle',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='bike_id',
            new_name='bike',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='stolenbike',
            old_name='bike_id',
            new_name='bike',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='http://placehold.it/250x250'),
        ),
    ]
