# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_user_token'),
        ('APP', '0003_auto_20161011_2339'),
    ]

    operations = [
    ]
