# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_auto_20161028_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='http://i.imgur.com/vDhhizN.jpg?1'),
        ),
    ]
